<?php
return [
    'machine_name' => 'Auth',
    'name' => 'Auth',
    'description' => 'Авторизация, сессии, настройки безопасности и управление входом',
    'version' => '1.0.0',
    'is_system' => 1,
    'dependencies' => ['Kernel' => '1.2.0'],
    'maintenance_providers' => ['\\Modules\\Auth\\Services\\AuthCleanupProvider'],
    'auth_provider' => \Modules\Auth\Services\AuthAuthenticationProvider::class,
    'routes' => [
        ['method' => 'GET', 'path' => '/login', 'controller' => '\\Modules\\Auth\\Controllers\\AuthController', 'action' => 'login', 'is_admin' => 0],
        ['method' => 'POST', 'path' => '/login', 'controller' => '\\Modules\\Auth\\Controllers\\AuthController', 'action' => 'attemptLogin', 'is_admin' => 0],
        ['method' => 'POST', 'path' => '/logout', 'controller' => '\\Modules\\Auth\\Controllers\\AuthController', 'action' => 'logout', 'is_admin' => 0],
        ['method' => 'GET', 'path' => '/admin/auth/settings', 'controller' => '\\Modules\\Auth\\Controllers\\AuthSettingsController', 'action' => 'index', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/settings', 'controller' => '\\Modules\\Auth\\Controllers\\AuthSettingsController', 'action' => 'save', 'is_admin' => 1],
        ['method' => 'GET', 'path' => '/admin/auth/ip-rules', 'controller' => '\\Modules\\Auth\\Controllers\\IpRulesController', 'action' => 'index', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/ip-rules', 'controller' => '\\Modules\\Auth\\Controllers\\IpRulesController', 'action' => 'add', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/ip-rules/delete/(:num)', 'controller' => '\\Modules\\Auth\\Controllers\\IpRulesController', 'action' => 'delete/$1', 'is_admin' => 1],
        ['method' => 'GET', 'path' => '/admin/auth/password', 'controller' => '\\Modules\\Auth\\Controllers\\PasswordController', 'action' => 'change', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/password', 'controller' => '\\Modules\\Auth\\Controllers\\PasswordController', 'action' => 'save', 'is_admin' => 1],
        ['method' => 'GET', 'path' => '/admin/auth/extensions', 'controller' => '\\Modules\\Auth\\Controllers\\AuthExtensionsController', 'action' => 'index', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/extensions/sync', 'controller' => '\\Modules\\Auth\\Controllers\\AuthExtensionsController', 'action' => 'sync', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/extensions/toggle/(:num)', 'controller' => '\\Modules\\Auth\\Controllers\\AuthExtensionsController', 'action' => 'toggle/$1', 'is_admin' => 1],
        ['method' => 'GET', 'path' => '/admin/auth/sessions', 'controller' => '\\Modules\\Auth\\Controllers\\SessionsController', 'action' => 'index', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/sessions/revoke/(:segment)', 'controller' => '\\Modules\\Auth\\Controllers\\SessionsController', 'action' => 'revoke/$1', 'is_admin' => 1],
        ['method' => 'POST', 'path' => '/admin/auth/sessions/revoke-others', 'controller' => '\\Modules\\Auth\\Controllers\\SessionsController', 'action' => 'revokeOthers', 'is_admin' => 1],
    ],
    'menu' => [
        ['title' => 'Безопасность входа', 'url' => '/admin/auth/settings', 'icon' => 'shield-lock', 'parent_key' => 'security', 'parent_title' => 'Безопасность', 'parent_weight' => 30, 'weight' => 40, 'is_system' => 1],
        ['title' => 'IP правила', 'url' => '/admin/auth/ip-rules', 'icon' => 'globe', 'parent_key' => 'security', 'parent_title' => 'Безопасность', 'parent_weight' => 30, 'weight' => 41, 'is_system' => 1],
        ['title' => 'Активные сессии', 'url' => '/admin/auth/sessions', 'icon' => 'shield', 'parent_key' => 'security', 'parent_title' => 'Безопасность', 'parent_weight' => 30, 'weight' => 42, 'is_system' => 1],
        ['title' => 'Сменить пароль', 'url' => '/admin/auth/password', 'icon' => 'key', 'parent_key' => 'security', 'parent_title' => 'Безопасность', 'parent_weight' => 30, 'weight' => 43, 'is_system' => 1],
        ['title' => 'Расширения Auth', 'url' => '/admin/auth/extensions', 'icon' => 'plug', 'parent_key' => 'security', 'parent_title' => 'Безопасность', 'parent_weight' => 30, 'weight' => 44, 'is_system' => 1],
    ],
];
